Loading menu + loading  changes (#64)
* adsf

* https://dabuttonfactory.com#t=New+Game&f=Open+Sans-Bold&ts=24&tc=fff&tshs=2&tshc=000&w=300&h=50&c=5&bgt=gradient&bgc=3d85c6&ebgc=000&it=png

* revert menu substate
Add filepicker

* feature complete

* l

* df

* lib verplaatst

* Changes to run settings (error c4996)

* Jeronimus zn feedback gefixt

* regex ff weg

* mac fix